### PR TITLE
[WIP] Debug pvs-report build failure

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
It does not, pvs-report fails: https://travis-ci.org/neovim/bot-ci/jobs/242625902.

**Comment by blueyed** [comment]
luarocks fails there:

```
/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/bin/luajit: ...ild/neovim/.deps/build/src/luarocks/src/luarocks/cfg.lua:78: attempt to index local 'site_config' (a boolean value)

stack traceback:
	...ild/neovim/.deps/build/src/luarocks/src/luarocks/cfg.lua:78: in main chunk
	[C]: in function 'require'
	src/bin/luarocks:4: in main chunk
	[C]: at 0x00403a60
make[4]: *** [run_luarocks] Error 1
```

(https://travis-ci.org/neovim/bot-ci/jobs/242625902#L2299)

**Comment by blueyed** [comment]
It seems to fail via `sh ./scripts/pvscheck.sh --deps --recheck .`, which was added in fdd11bf by @ZyX-I.
https://github.com/neovim/bot-ci/blob/462dc0aaa27fa0c255ca079ebf68c472cbb0096a/ci/pvs-report.sh#L39

**Comment by justinmk** [comment]
Root cause is likely same as the others: with_token

**Comment by jamessan** [comment]
The parallel builds seem to be causing problems with third-party:

```
Scanning dependencies of target mpack
make[3]: Leaving directory `/home/travis/build/neovim/bot-ci/build/neovim/.deps'
make[3]: Entering directory `/home/travis/build/neovim/bot-ci/build/neovim/.deps'
[ 79%] yes
checking for objdir... Generating usr/lib/luarocks/rocks/mpack
make[3]: usr/bin/luarocks: Command not found
make[3]: *** [usr/lib/luarocks/rocks/mpack] Error 127
```

BuildLua.cmake is supposed to serialize everything to avoid this, so it's not clear what the problem is.  The third-party builds work for normal CI, but when run for the pvs-report build it is highly parallel (`make -j33 ...`).

**Comment by justinmk** [comment]
Can we just de-parallelize it? It only runs once per day...

**Comment by jamessan** [comment]
That might work around the issue, but this implies there's something wrong with our CMakeLists.txt for third-party which could affect anyone else running parallel makes.

**Comment by justinmk** [comment]
`-j33` does not make   sense for travis, so at least part of the problem is `pvscheck.sh:echo_jobs_num()`.

**Comment by justinmk** [comment]
cc @ZyX-I  With https://github.com/neovim/neovim/commit/4b08b5d1942ac12c54b959ec4bb2c5e13b2de587 the pvscheck.sh scripts gets farther, now some problem with the call to `pvs-studio-analyzer`:

```
+get_jobs_num
./scripts/pvscheck.sh: 343: ./scripts/pvscheck.sh: get_jobs_num: not found
+pvs-studio-analyzer analyze --threads  --output-file PVS-studio.log --verbose --file build/compile_commands.json --sourcetree-root .
Unknown option 
pvs-studio-analyzer analyze [flags]

    Launch PVS-Studio for your project.

    -l FILE, --lic-file FILE
        PVS-Studio license file.
    -j N, --threads N (default: 1)
        Allow N PVS-Studio analyzers at once.
    -o FILE, --output-file FILE
        Place the analyzer's report into FILE.
    -c FILE, --cfg FILE
        Run PVS using config FILE.
    -v, --verbose
        Use the detailed logging mode.
    -f FILE, --file FILE (default: 'compile_commands.json', 'strace_out')
        Use trace output or compile commands database FILE.
    -C COMPILER_NAME, --compiler COMPILER_NAME
        Filter compiler commands by compiler name.
    -E VAR=VALUE, --env VAR=VALUE
        Modify environment for preprocessor.
    -e DIR, --exclude-path DIR
        Directory whose files are not necessary to check.
    -a MODE, --analysis-mode MODE (default: 4)
        MODE defines the type of warnings. 4 - General Analysis.
    -r DIR, --sourcetree-root DIR
        Replace absolute paths in report with relative paths.
    -h, --help
        The analyze command help.
    --preprocessor NAME (default: <auto-detected>)
        Preprocessor (gcc or clang).
    --platform NAME (default: linux64)
        Platform (linux64, linux32, x64, Win32, arm).
```

**Comment by justinmk** [comment]
Oh, an incomplete function rename...

**Comment by blueyed** [comment]
Let's close this test-PR (which is empty anyway).

**Pull request closed without merging**
