### PR TITLE
release: generate macOS package

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Comment by tweekmonster** [comment]
Just tried the macOS release and it worked on 10.11.  I took a look at its shared libraries and noticed something different from the one I created:

```sh
$ otool -L nvim                                                                                                                                                                                                                                            02:29:03
nvim:
	@executable_path/libs/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	@executable_path/libs/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	@executable_path/libs/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

It doesn't reference `/usr/local/opt/gettext/lib/libintl.8.dylib`.  The ones listed above are from `/usr/lib` which is part of the OS, so they might not even need to be changed (or could be changed to `@rpath`) if the target OS version is low enough.

**Comment by justinmk** [comment]
Hmm, maybe need to install libintl on bot-ci ?

**Comment by tweekmonster** [comment]
I thought that it meant that libintl was statically linked.  I'm going to try and setup a bare 10.8 VM to see if it runs the binary.

Something I forgot to mention is that the release looks for runtime files in `/share/nvim`.  Maybe those should ship with the release?

**Comment by justinmk** [comment]
For sure

**Comment by tweekmonster** [comment]
Took the release binary and rewrote the lib paths to point back to `/usr/lib`

```sh
$ otool -L ./nvim
./nvim:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Ran it on a fresh install of OS X 10.8 (Mountain Lion).  I tried running `:language en` and got `E319: The command is not available in this version`.  On my local copy, it shows: `E197: Cannot set language to "en"`.

screenshot

screenshot-1

**Comment by tweekmonster** [comment]
To be clear: I tested this on a clean install with no development tools or thirdparty libraries installed.

**Comment by justinmk** [comment]
Really nice that it runs on 10.8. Hopefully the lang command will be fixed by libintl.

**Pull request merged**
