### PR TITLE
clang-report: Fix failure when only one issue.

### PR DESCRIPTION
**Pull request by elmart**

### CODE REVIEW

**Comment by elmart** [comment]
Restarted clang-report build failed again.
But I'd say it probably didn't pick the latest script version, but the forme one.

**Comment by fwalch** [comment]
It did:

```
$ cd neovim/bot-ci
$ git checkout -qf 4f182017f6db312a7f32fd460591848c8ccdb9cc
```

Travis seems to have some problems currently: http://www.traviscistatus.com

**Comment by elmart** [comment]
Latest script version is 7f4f7f7fe85023f5c55870d05d3a8d9e358656c2.
The one you reported is the previous one.

**Comment by fwalch** [comment]
Yes, that's what I meant, sorry for the confusing wording.

**Comment by elmart** [comment]
Ah, ok. So, that means restarting the build is not going to work, no matter how many times we try. We need a new build for it to work.

**Comment by justinmk** [comment]
@elmart @fwalch I think it's corrected now.

**Comment by elmart** [comment]
Yes, now it only remains for Travis to work ok to complete the full build.
They are failing too much lately...

Thanks guys.

**Pull request merged**
