### PR TITLE
Ignore xdiff folder when reporting clang errors.

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by justinmk** [comment]
i don't think this repo is the source of truth anymore, that's why i linked to https://github.com/neovim/doc/ :)

@jamessan should we delete `ci/clang-report.sh` from bot-ci to avoid confusion ?

**Comment by jamessan** [comment]
> @jamessan should we delete ci/clang-report.sh from bot-ci to avoid confusion ?

Sure

**Comment by justinmk** [comment]
> > @jamessan should we delete ci/clang-report.sh from bot-ci to avoid confusion ?
> 
> Sure

inverted question, which files should _not_ be deleted from bot-ci at this point? (I don't know how many repos the bot scripts are now spread across...)

**Comment by jamessan** [comment]
Ah, I guess I hadn't done any cleanup of the scripts here yet. I was thinking of the Travis config in neovim/neovim.

**Pull request closed without merging**
