### PR TITLE
Fix nightly

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
@justinmk 
Can you try the `set -x` on a build not from a PR, please?
Or add me to the org so that I could trigger a non-PR build to debug this further.

**Comment by justinmk** [comment]
@blueyed Added you to org, but please don't commit to master yet. I have a local change that should fix the linux nightly build (not macOS).

**Comment by blueyed** [comment]
@justinmk 
Thanks!
I won't commit to master directly.
Curious about your fix, please push it.

I've pushed to https://github.com/neovim/bot-ci/tree/fix-nightly for now.

**Comment by blueyed** [comment]
"push" fails, "pr" is ok.

**Comment by justinmk** [comment]
Looks like you pushed to a branch on this repo, that's what the extra "/push" build is for.

**Comment by blueyed** [comment]
@justinmk 
Yes, that was intentional.. the "push" build will have the secret key etc, but a PR has not.

**Comment by jamessan** [comment]
@justinmk and I worked through this and nightly builds are working again.

**Comment by blueyed** [comment]
Thanks a lot!

**Pull request closed without merging**
