### PR TITLE
Fix PVS build

### PR DESCRIPTION
**Pull request by ZyX-I**

### CODE REVIEW

**Comment by justinmk** [comment]
Sorry, in my sed change I forgot to use `${GH_TOKEN:-}`.

**Comment by ZyX-I** [comment]
@justinmk You also forgot that `has_gh_token` needs return status from xargs.

**Comment by ZyX-I** [comment]
This is more likely to cause problems because in that function you either fail *before* entering the loop or have GH_TOKEN defined.

**Comment by ZyX-I** [comment]
By the way, is autocancellation enabled here?

**Comment by justinmk** [comment]
Enabled auto-cancel

**Comment by ZyX-I** [comment]
pvs-report finally compiled.

**Comment by ZyX-I** [comment]
Something is wrong with clang and pvs badges.

**Comment by ZyX-I** [comment]
The command it uses to download badge (`curl --tlsv1 https://img.shields.io/badge/PVS_analysis-34-ff0000.svg`, copied from trace) works fine locally (BTW, missing escaping). `local reports_dir=/home/travis/build/neovim/bot-ci/build/doc//reports/pvs` looks fine as well. `test -f` test I inherited from previous code looks useless, `>` will always create something.

Ah, got it: I moved `2>&1` from the start to the end of the command altering the meaning in process.

**Pull request merged**
